ALTER TABLE loans ADD COLUMN IF NOT EXISTS rejection_message TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rejected_by UUID REFERENCES users(id);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
